#!/usr/bin/env python3
"""
Embed every PNG in assets/ as a base64 data: URI into a generated JS module.

Why: a WebGL game opened directly from disk (file://) cannot upload external
image files as textures — the browser taints them as cross-origin. data: URIs
are same-origin, so embedding makes the bundled game run by simply
double-clicking index.html (and also removes all network requests over HTTP).

The large character sheets are downscaled slightly (they render small as
billboards) to keep the bundle lean. Keys are the asset's repo-relative path,
matching the paths in src/config/assets.js, so the loader can look them up 1:1.

Usage:  python3 tools/embed_assets.py
"""
import os
import io
import base64
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(ROOT, "assets")
OUT = os.path.join(ROOT, "src", "generated", "assets_data.js")
os.makedirs(os.path.dirname(OUT), exist_ok=True)

SHEET_SCALE = 0.75   # 512x1024 walk sheets -> 384x768 (cells 128x192, plenty)


def encode(path):
    rel = os.path.relpath(path, ROOT).replace(os.sep, "/")
    im = Image.open(path)
    # downscale only the big character sheets
    if im.width >= 512 and im.height >= 1024:
        im = im.convert("RGBA").resize(
            (int(im.width * SHEET_SCALE), int(im.height * SHEET_SCALE)), Image.BILINEAR)
        buf = io.BytesIO(); im.save(buf, "PNG", optimize=True)
        data = buf.getvalue()
    else:
        with open(path, "rb") as fh:
            data = fh.read()
    b64 = base64.b64encode(data).decode("ascii")
    return rel, f"data:image/png;base64,{b64}", len(data)


def main():
    files = []
    for dp, _dn, fns in os.walk(ASSETS):
        for fn in fns:
            if fn.lower().endswith(".png"):
                files.append(os.path.join(dp, fn))
    files.sort()

    total = 0
    lines = [
        "// AUTO-GENERATED by tools/embed_assets.py — do not edit by hand.",
        "// Every game asset embedded as a data: URI so the bundle is fully",
        "// self-contained and runs from file:// (double-click) or any server.",
        "export const EMBEDDED = {",
    ]
    for p in files:
        rel, uri, n = encode(p)
        total += n
        lines.append(f'  {rel!r}: {uri!r},')
    lines.append("};")
    lines.append("")
    with open(OUT, "w") as fh:
        fh.write("\n".join(lines))
    print(f"Embedded {len(files)} assets ({total/1024:.0f} KB raw) -> {os.path.relpath(OUT, ROOT)}")
    print(f"Generated module size: {os.path.getsize(OUT)/1024:.0f} KB")


if __name__ == "__main__":
    main()
